// Renders the release-pipeline state-machine diagram from a build-time-generated
// SVG. The source diagram is `lib/workflows/pipeline-diagram.ts`; the SVG is
// regenerated by `pnpm gen:workflow-graph` (run automatically as `pnpm prebuild`).

export function WorkflowGraph() {
  return (
    <div className="rounded-md border border-border bg-bg-secondary p-4">
      <div className="mb-3 flex items-baseline gap-3">
        <h3 className="text-sm font-semibold text-text-primary">Release pipeline state machine</h3>
        <span className="text-xs text-text-tertiary">
          Source of truth: <code className="font-mono">lib/workflows/</code>
        </span>
      </div>
      <div className="overflow-x-auto">
        <img src="/workflow-graph.svg" alt="Release pipeline state machine" className="w-full max-w-full" />
      </div>
    </div>
  );
}
